//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASLRD_r3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class adresse
    {
        public int adresseID { get; set; }
        public string ville { get; set; }
        public string rue { get; set; }
        public int codepostal { get; set; }
        public string clientID { get; set; }
        public Nullable<int> restaurantID { get; set; }
    
        public virtual client client { get; set; }
        public virtual restaurant restaurant { get; set; }
    }
}
