//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASLRD_r3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class adresse
    {
        public int adresseID { get; set; }
        public string ville { get; set; }
        public string rue { get; set; }
        public int codepostal { get; set; }
        public string clientID { get; set; }
        public Nullable<int> restaurantID { get; set; }
    
        public virtual client client { get; set; }
        public virtual restaurant restaurant { get; set; }
    }
}
