//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASLRD_r3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class commande
    {
        public commande()
        {
            this.detailcommande = new HashSet<detailcommande>();
            this.detailcommandetmp = new HashSet<detailcommandetmp>();
        }
    
        public int commandeID { get; set; }
        public decimal prixtotal { get; set; }
        public Nullable<decimal> fraisdelivraison { get; set; }
        public Nullable<double> reduction { get; set; }
        public System.DateTime datecommande { get; set; }
        public string etatcommande { get; set; }
    
        public virtual ICollection<detailcommande> detailcommande { get; set; }
        public virtual ICollection<detailcommandetmp> detailcommandetmp { get; set; }
    }
}
