//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASLRD_r3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class commentaire
    {
        public int commentaireID { get; set; }
        public string commentaire1 { get; set; }
        public Nullable<int> note { get; set; }
        public System.DateTime datecommentaire { get; set; }
        public Nullable<int> restaurantID { get; set; }
        public string clientID { get; set; }
        public Nullable<int> produitID { get; set; }
        public Nullable<int> menuID { get; set; }
    
        public virtual client client { get; set; }
        public virtual produit produit { get; set; }
        public virtual menu menu { get; set; }
        public virtual restaurant restaurant { get; set; }
    }
}
