//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASLRD_r3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class commande
    {
        public commande()
        {
            this.detailcommande = new HashSet<detailcommande>();
            this.detailcommandetmp = new HashSet<detailcommandetmp>();
        }
    
        public int commandeID { get; set; }
        public decimal prixtotal { get; set; }
        public Nullable<decimal> fraisdelivraison { get; set; }
        public Nullable<double> reduction { get; set; }
        public System.DateTime datecommande { get; set; }
        public string etatcommande { get; set; }
    
        public virtual ICollection<detailcommande> detailcommande { get; set; }
        public virtual ICollection<detailcommandetmp> detailcommandetmp { get; set; }
    }
}
