//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASLRD_r3.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class commentaire
    {
        public commentaire()
        {
            this.menu = new HashSet<menu>();
            this.produit = new HashSet<produit>();
        }
    
        public int commentaireID { get; set; }
        public string commentaire1 { get; set; }
        public Nullable<int> note { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime datecommentaire { get; set; }
        public Nullable<int> restaurantID { get; set; }
        public string clientID { get; set; }
    
        public virtual client client { get; set; }
        public virtual restaurant restaurant { get; set; }
        public virtual ICollection<menu> menu { get; set; }
        public virtual ICollection<produit> produit { get; set; }
    }
}
