//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASLRD_r3.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseASLRD2Entities : DbContext
    {
        public DataBaseASLRD2Entities()
            : base("name=DataBaseASLRD2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<adresse> adresse { get; set; }
        public DbSet<client> client { get; set; }
        public DbSet<commande> commande { get; set; }
        public DbSet<commentaire> commentaire { get; set; }
        public DbSet<detailcommande> detailcommande { get; set; }
        public DbSet<detailcommandetmp> detailcommandetmp { get; set; }
        public DbSet<ingredient> ingredient { get; set; }
        public DbSet<menu> menu { get; set; }
        public DbSet<ouverture> ouverture { get; set; }
        public DbSet<produit> produit { get; set; }
        public DbSet<restaurant> restaurant { get; set; }
    }
}
