//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASLRD_r3.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseASLRDEntities : DbContext
    {
        public DataBaseASLRDEntities()
            : base("name=DataBaseASLRDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<adresse> adresse { get; set; }
        public DbSet<client> client { get; set; }
        public DbSet<commande> commande { get; set; }
        public DbSet<commentaire> commentaire { get; set; }
        public DbSet<detailcommande> detailcommande { get; set; }
        public DbSet<detailcommandetmp> detailcommandetmp { get; set; }
        public DbSet<ingredient> ingredient { get; set; }
        public DbSet<menu> menu { get; set; }
        public DbSet<ouverture> ouverture { get; set; }
        public DbSet<produit> produit { get; set; }
        public DbSet<restaurant> restaurant { get; set; }
    }
}
