//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASLRD_r3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class detailcommandetmp
    {
        public detailcommandetmp()
        {
            this.menu = new HashSet<menu>();
            this.produit = new HashSet<produit>();
        }
    
        public int detailcommandetmpID { get; set; }
        public string sessionID { get; set; }
        public int quantitee { get; set; }
        public Nullable<double> reduction { get; set; }
        public System.DateTime datedetailcommande { get; set; }
        public int restaurantID { get; set; }
        public int commandeID { get; set; }
    
        public virtual commande commande { get; set; }
        public virtual restaurant restaurant { get; set; }
        public virtual ICollection<menu> menu { get; set; }
        public virtual ICollection<produit> produit { get; set; }
    }
}
