//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASLRD_r3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingredient
    {
        public ingredient()
        {
            this.produit = new HashSet<produit>();
        }
    
        public int ingredientID { get; set; }
        public string nom { get; set; }
        public Nullable<double> quantite { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<produit> produit { get; set; }
    }
}
