//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASLRD_r3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public menu()
        {
            this.commentaire = new HashSet<commentaire>();
            this.detailcommande = new HashSet<detailcommande>();
            this.detailcommandetmp = new HashSet<detailcommandetmp>();
            this.produit = new HashSet<produit>();
        }
    
        public int menuID { get; set; }
        public string nom { get; set; }
        public decimal prixmenu { get; set; }
        public string description { get; set; }
        public Nullable<System.TimeSpan> delais { get; set; }
        public Nullable<double> reduction { get; set; }
        public int restaurantID { get; set; }
    
        public virtual ICollection<commentaire> commentaire { get; set; }
        public virtual ICollection<detailcommande> detailcommande { get; set; }
        public virtual ICollection<detailcommandetmp> detailcommandetmp { get; set; }
        public virtual restaurant restaurant { get; set; }
        public virtual ICollection<produit> produit { get; set; }
    }
}
