//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASLRD_r3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ouverture
    {
        public int ouvertureID { get; set; }
        public string jour { get; set; }
        public System.TimeSpan heure_douverture { get; set; }
        public System.TimeSpan heure_de_fermeture { get; set; }
        public Nullable<System.DateTime> jour_ferme { get; set; }
        public int restaurantID { get; set; }
    
        public virtual restaurant restaurant { get; set; }
    }
}
