//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASLRD_r3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ouverture
    {
        public int ouvertureID { get; set; }
        public string jour { get; set; }
        public System.TimeSpan heure_douverture { get; set; }
        public System.TimeSpan heure_de_fermeture { get; set; }
        public Nullable<System.DateTime> jour_ferme { get; set; }
        public int restaurantID { get; set; }
    
        public virtual restaurant restaurant { get; set; }
    }
}
