//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASLRD_r3.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class produit
    {
        public produit()
        {
            this.commentaire = new HashSet<commentaire>();
            this.detailcommande = new HashSet<detailcommande>();
            this.detailcommandetmp = new HashSet<detailcommandetmp>();
            this.ingredient = new HashSet<ingredient>();
            this.menu = new HashSet<menu>();
        }

        [DisplayName("N° produit")]
        public int produitID { get; set; }
        [DisplayName("Nom")]
        public string nom { get; set; }
        [DisplayName("Prix")]
        public decimal prixproduit { get; set; }
        [DisplayName("Description")]
        public string description { get; set; }
        [DisplayName("Délais")]
        public Nullable<System.TimeSpan> delais { get; set; }
        [DisplayName("Réduction")]
        public Nullable<double> reduction { get; set; }
        [DisplayName("Restaurant")]
        public int restaurantID { get; set; }
    
        public virtual ICollection<commentaire> commentaire { get; set; }
        public virtual ICollection<detailcommande> detailcommande { get; set; }
        public virtual ICollection<detailcommandetmp> detailcommandetmp { get; set; }
        public virtual restaurant restaurant { get; set; }
        public virtual ICollection<ingredient> ingredient { get; set; }
        public virtual ICollection<menu> menu { get; set; }
    }
}
