//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASLRD_r3.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class restaurant
    {
        public restaurant()
        {
            this.adresse = new HashSet<adresse>();
            this.commentaire = new HashSet<commentaire>();
            this.detailcommande = new HashSet<detailcommande>();
            this.detailcommandetmp = new HashSet<detailcommandetmp>();
            this.menu = new HashSet<menu>();
            this.ouverture = new HashSet<ouverture>();
            this.produit = new HashSet<produit>();
        }

        [DisplayName("N du restaurant")]
        public int restaurantID { get; set; }
        [DisplayName("Adresse mail")]
        public string email { get; set; }
        [DisplayName("Mot de passe")]
        public string motdepasse { get; set; }
        [DisplayName("Nom")]
        public string nom { get; set; }
        [DisplayName("Téléphone")]
        public Nullable<int> telephone { get; set; }
        [DisplayName("Status")]
        public string status { get; set; }
        [DisplayName("Genre")]
        public string genre { get; set; }
        [DisplayName("N siret")]
        public string nsiret { get; set; }
    
        public virtual ICollection<adresse> adresse { get; set; }
        public virtual ICollection<commentaire> commentaire { get; set; }
        public virtual ICollection<detailcommande> detailcommande { get; set; }
        public virtual ICollection<detailcommandetmp> detailcommandetmp { get; set; }
        public virtual ICollection<menu> menu { get; set; }
        public virtual ICollection<ouverture> ouverture { get; set; }
        public virtual ICollection<produit> produit { get; set; }
    }
}
